### ISSUE TITLE
Method never cached via file caching, no cache files and profiler telling cache never gets hit

### ISSUE THREAD

**Issue by martijn80** [phpro/annotated-cache-bundle#2]
Hi guys, 

I'm trying to use this bundle in Symfony 3.4 to file cache a service. The original method keeps being called, instead of the cache and when I look into the profiler (via app_dev.php), I never see any cache hits, only misses. The cache dirs are being made, but there are no files in it. The generated cache key I see in the profiler is the same for identical calls, so that looks okay.

I have followed the readme, added this bundle via composer and added psr6 pool cache from symfony as well via composer require symfony/cache.

These are the relevant parts of my config.yml :
```yml
services:
    mbz_cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        # zero means store indefinitely
        arguments: ['', 0, "%kernel.cache_dir%/mbz/"]
    mbz_service:
        public: true
        class: AppBundle\Service\Mbz
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: 'annotated_cache.eligable' }
annotated_cache:
    key_generator: phpro.annotated_cache.keygenerator.expressions
    proxy_config:
        cache_dir: '%kernel.cache_dir%/annotated_cache'
        namespace: AnnotatedCacheGeneratedProxy
        register_autoloader: true
    pools:
        mbz:
            service: mbz_cache
```
The mbz_service method I want to cache has this annotation: 
```php
<?php
namespace AppBundle\Service;

class Mbz 
{
	/**
	  * @Cacheable(
	  *     pools = "mbz",
	  *     ttl   = 0
	  * )
	  */
	public function search($param)
	{
		echo "this should not be displayed the second time this method is called, becasue it's cached, right?";
		return date('Y-m-d H:i:s');
	}
}
```
If the cache works, you should see an outdated datetime and no echo, but I do see an echo and the timestamp is refreshed everytime. 

What am I overseeing?
Cheers.
